name: Generate and Push Swagger Documentation

on:
  push:
    branches:
      - master
      - test
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install FastAPI and Pydantic
        run: |
          python -m pip install --upgrade pip
          pip install "fastapi[standard]" pydantic

      - name: Generate Swagger API documentation
        run: |
          mkdir -p ./api-rtr
          python script.py

      - name: Remove pycache files
        run: |
          rm -rf app/__pycache__

      - name: Verify openapi.json exists
        run: |
          if [ ! -f ./api-rtr/openapi.json ]; then
            echo "openapi.json not found!"
            exit 1
          else
            echo "openapi.json generated successfully."
          fi

      - name: Move openapi.json to docs
        run: |
          mkdir -p ./docs
          mv ./api-rtr/openapi.json ./docs/openapi.json

      - name: Clean untracked files
        run: git clean -fd

      - name: Checkout docs branch and resolve conflicts
        run: |
          git fetch origin docs
          git checkout --track origin/docs || git checkout -b docs --
          git pull origin docs --rebase || git pull origin docs --no-rebase

      - name: Add untracked files
        run: |
          git add ./docs/openapi.json

      - name: Commit and push docs update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update Swagger documentation" || echo "Nothing to commit"
          git push origin docs --force-with-lease