name: Generate and Push Swagger Documentation

on:
  push:
    branches:
      - master
      - test
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install FastAPI and Pydantic
        run: |
          python -m pip install --upgrade pip
          pip install "fastapi[standard]" pydantic

      - name: Create directory for OpenAPI
        run: mkdir -p ./api-rtr

      - name: Generate Swagger API documentation
        run: python script.py

      - name: Verify openapi.json exists
        run: |
            if [ ! -f ./api-rtr/openapi.json ]; then
              echo "openapi.json not found!"
              exit 1
            else
              echo "openapi.json generated successfully."
            fi

      - name: Checkout docs branch
        run: |
            git fetch origin docs
            git checkout docs || git checkout -b docs


      - name: Commit and push docs update
        run: |
          git add api-rtr/openapi.json
          git commit -m "Update Swagger documentation"
          git push origin docs

